# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("renderer") {
  sources = [
    "aurelian_render_frame_observer.cc",
    "aurelian_render_frame_observer.h",
  ]

  deps = [
    "//aurelian:aurelian_capability",
    "//aurelian/public/mojom",
    "//base",
    "//content/public/renderer",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public:blink",
    "//third_party/blink/public/common",
    "//v8",
  ]
}
