// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef AURELIAN_CATALOG_CDP_CATALOG_H_
#define AURELIAN_CATALOG_CDP_CATALOG_H_

#include <optional>
#include <string>
#include <vector>

#include "base/no_destructor.h"
#include "base/values.h"

namespace aurelian {

// ACM-S2 (AURELIAN-GENERIC-CONTROL-TDD-PLAN Phase 0): the embedded CDP
// descriptor + the DERIVED session-context table + the AUTHORED
// per-command override list, parsed once and served as the catalog the
// ACM-1 mirror projects from. The descriptor is the build-generated
// merged protocol.json (design section 2: the catalog Chromium maintains
// about itself, version-locked to the binary); the session-context rows
// come from aurelian/catalog/session_context_table.json, generated by
// derive_session_context.py from the three browser-process registration
// sites and drift-locked by the build-time regeneration audit.
class CdpCatalog {
 public:
  // The session-context row for one descriptor domain. Rows apply to
  // the browser mirror + page/frame target sub-mirrors ONLY; non-page
  // target types (tab/worker/worklet) are annotation-not-applicable
  // (design section 2 round-8).
  struct ContextRow {
    bool in_browser_union = false;
    bool browser_only = false;
    bool conditional = false;
  };

  // Parses the embedded data on first use. CHECK-fails on malformed
  // embedded JSON (fail fast: the data is build-generated, so malformed
  // means the build is broken, not the input).
  static const CdpCatalog& Get();

  CdpCatalog(const CdpCatalog&) = delete;
  CdpCatalog& operator=(const CdpCatalog&) = delete;

  size_t domain_count() const { return domains_.size(); }
  size_t command_count() const { return command_count_; }
  size_t event_count() const { return event_count_; }

  const std::vector<std::string>& domains() const { return domains_; }

  // The descriptor entry for `domain`, or nullptr.
  const base::DictValue* FindDomain(const std::string& domain) const;

  // The descriptor entry for `domain`.`command`, or nullptr.
  const base::DictValue* FindCommand(const std::string& domain,
                                       const std::string& command) const;

  // The descriptor entry for `domain`'s event `event`, or nullptr.
  const base::DictValue* FindEvent(const std::string& domain,
                                     const std::string& event) const;

  // The command / event names of `domain`, descriptor order (empty for a
  // non-descriptor domain).
  std::vector<std::string> CommandsOf(const std::string& domain) const;
  std::vector<std::string> EventsOf(const std::string& domain) const;

  // The first command name of `domain` (descriptor order), or nullopt.
  std::optional<std::string> FirstCommandOf(const std::string& domain) const;

  // The derived session-context row; nullopt only for a non-descriptor
  // domain name.
  std::optional<ContextRow> ContextFor(const std::string& domain) const;

  // Descriptor domains whose derived row is browser_only, sorted.
  std::vector<std::string> BrowserOnlyDomains() const;

  // The authored override context for "Domain.command", or nullopt.
  std::optional<std::string> OverrideContextFor(
      const std::string& qualified_command) const;
  std::vector<std::string> OverrideCommands() const;

 private:
  friend class base::NoDestructor<CdpCatalog>;

  CdpCatalog();
  ~CdpCatalog();

  base::DictValue descriptor_;
  base::DictValue table_;
  base::DictValue overrides_;
  std::vector<std::string> domains_;
  size_t command_count_ = 0;
  size_t event_count_ = 0;
};

}  // namespace aurelian

#endif  // AURELIAN_CATALOG_CDP_CATALOG_H_
