#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Embed the CDP descriptor + session-context data as C++ constants.

AURELIAN-GENERIC-CONTROL-DESIGN.md section 4: the descriptor is embedded
as DATA, regenerated with every Chromium roll, so the mirror tracks
upstream by construction. One generated TU carries four constants:

  kCdpProtocolJson        - the build-generated merged protocol.json
  kSessionContextJson     - the derived domain table (checked in;
                            regeneration audit fails the build on drift)
  kCommandOverridesJson   - the AUTHORED per-command override list
  kRendererServedJson     - pin-verified browser-only corrections
"""

import argparse


def emit(name, path, out):
    with open(path, "rb") as f:
        data = f.read()
    out.write("const char %s[] = {\n" % name)
    for i in range(0, len(data), 20):
        out.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    out.write("  0};\n")
    out.write("const size_t %s_size = %d;\n\n" % (name, len(data)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--protocol", required=True)
    ap.add_argument("--table", required=True)
    ap.add_argument("--overrides", required=True)
    ap.add_argument("--renderer-served", required=True)
    ap.add_argument("--out-cc", required=True)
    ap.add_argument("--out-h", required=True)
    args = ap.parse_args()

    with open(args.out_h, "w", encoding="utf-8") as h:
        h.write(
            "// GENERATED by aurelian/catalog/embed_json.py - do not edit.\n"
            "#ifndef AURELIAN_CATALOG_EMBEDDED_CATALOG_DATA_H_\n"
            "#define AURELIAN_CATALOG_EMBEDDED_CATALOG_DATA_H_\n\n"
            "#include <stddef.h>\n\n"
            "namespace aurelian {\n"
            "extern const char kCdpProtocolJson[];\n"
            "extern const size_t kCdpProtocolJson_size;\n"
            "extern const char kSessionContextJson[];\n"
            "extern const size_t kSessionContextJson_size;\n"
            "extern const char kCommandOverridesJson[];\n"
            "extern const size_t kCommandOverridesJson_size;\n"
            "extern const char kRendererServedJson[];\n"
            "extern const size_t kRendererServedJson_size;\n"
            "}  // namespace aurelian\n\n"
            "#endif  // AURELIAN_CATALOG_EMBEDDED_CATALOG_DATA_H_\n")

    with open(args.out_cc, "w", encoding="utf-8") as cc:
        cc.write(
            "// GENERATED by aurelian/catalog/embed_json.py - do not edit.\n"
            "#include \"aurelian/catalog/embedded_catalog_data.h\"\n\n"
            "namespace aurelian {\n\n")
        emit("kCdpProtocolJson", args.protocol, cc)
        emit("kSessionContextJson", args.table, cc)
        emit("kCommandOverridesJson", args.overrides, cc)
        emit("kRendererServedJson", args.renderer_served, cc)
        cc.write("}  // namespace aurelian\n")


if __name__ == "__main__":
    main()
